using Loom.Config;
using Version = Loom.Config.Version;

namespace Loom.Testing;

/// <summary>
///     The lock file is the seam between a package manager and the compiler: the manifest says which versions are
///     acceptable, the lock says which ones were chosen. These cover both directions of that file — what a package
///     manager writes and what a build reads back — since a format only one side agrees with is no contract at all.
/// </summary>
public class LockFileTest
{
    private const string FullLock =
        """
        version = 1

        [[package]]
        name = "serio"
        version = "1.2.3"
        source = "https://loom-lang.github.io/index"
        checksum = "sha256:abc123"
        dependencies = ["alternativelua/tether"]

        [[package]]
        name = "alternativelua/tether"
        version = "0.3.1"
        """;

    [Fact]
    public void Read_FullLock_ReadsEveryField()
    {
        var lockFile = ReadValid(FullLock);

        Assert.Equal(LockFile.CurrentFormatVersion, lockFile.FormatVersion);
        var serio = lockFile.Find(PackageName.Parse("serio"));
        Assert.NotNull(serio);
        Assert.Equal(Version.Parse("1.2.3"), serio.Version);
        Assert.Equal("https://loom-lang.github.io/index", serio.Source);
        Assert.Equal("sha256:abc123", serio.Checksum);
        Assert.Equal([PackageName.Parse("alternativelua/tether")], serio.Dependencies);

        var tether = lockFile.Find(PackageName.Parse("alternativelua/tether"));
        Assert.NotNull(tether);
        Assert.Null(tether.Source);
        Assert.Null(tether.Checksum);
        Assert.Empty(tether.Dependencies);
    }

    [Fact]
    public void Read_LooksUpAPackageTheWayItsNameCompares() =>
        Assert.NotNull(ReadValid(FullLock).Find(PackageName.Parse("AlternativeLua/Tether")));

    [Fact]
    public void Read_UnlockedPackage_IsNotFound() => Assert.Null(ReadValid(FullLock).Find(PackageName.Parse("runit")));

    /// <remarks>
    ///     A source is where a version came from, and an index is as legitimately a directory beside the project as
    ///     it is a registry over http — the same rule <c>[registry] index</c> is read by.
    /// </remarks>
    [Theory]
    [InlineData("https://loom-lang.github.io/index")]
    [InlineData("../index")]
    [InlineData("/srv/loom/index")]
    public void Read_AcceptsAnySourceAnIndexCouldBe(string source) =>
        Assert.Equal(
            source,
            ReadValid($"version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\nsource = \"{source}\"\n")
                .Find(PackageName.Parse("serio"))!
                .Source
        );

    [Fact]
    public void Read_LockWithoutPackages_IsAProjectThatResolvedToNothing() => Assert.Empty(ReadValid("version = 1\n").Packages);

    [Fact]
    public void ToToml_RoundTripsEveryField()
    {
        var lockFile = ReadValid(FullLock);

        var reread = ReadValid(lockFile.ToToml());

        Assert.Equal(lockFile.Packages.Select(package => package.ToString()), reread.Packages.Select(package => package.ToString()));
        var serio = reread.Find(PackageName.Parse("serio"));
        Assert.NotNull(serio);
        Assert.Equal("https://loom-lang.github.io/index", serio.Source);
        Assert.Equal("sha256:abc123", serio.Checksum);
        Assert.Equal([PackageName.Parse("alternativelua/tether")], serio.Dependencies);
    }

    /// <remarks>A committed file two machines write is only useful if they write it the same way.</remarks>
    [Fact]
    public void ToToml_OrdersPackagesByName_WhateverOrderTheyWereGivenIn()
    {
        var lockFile = new LockFile(
            [
                new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3")),
                new LockedPackage(PackageName.Parse("alternativelua/tether"), Version.Parse("0.3.1")),
                new LockedPackage(PackageName.Parse("runit"), Version.Parse("0.4.0"))
            ]
        );

        Assert.Equal(["runit", "serio", "alternativelua/tether"], lockFile.Packages.Select(package => package.Name.ToString()));
        Assert.Equal(
            """
            # Generated by a Loom package manager. Commit this file; do not edit it by hand.
            version = 1

            [[package]]
            name = "runit"
            version = "0.4.0"

            [[package]]
            name = "serio"
            version = "1.2.3"

            [[package]]
            name = "alternativelua/tether"
            version = "0.3.1"

            """.ReplaceLineEndings("\n"),
            lockFile.ToToml()
        );
    }

    [Fact]
    public void ToToml_OrdersAndDeduplicatesTheDependenciesOfAPackage()
    {
        var lockFile = new LockFile(
            [
                new LockedPackage(
                    PackageName.Parse("serio"),
                    Version.Parse("1.2.3"),
                    dependencies: [PackageName.Parse("runit"), PackageName.Parse("alternativelua/tether"), PackageName.Parse("RunIt")]
                ),
                new LockedPackage(PackageName.Parse("runit"), Version.Parse("0.4.0")),
                new LockedPackage(PackageName.Parse("alternativelua/tether"), Version.Parse("0.3.1"))
            ]
        );

        Assert.Contains("dependencies = [\"runit\", \"alternativelua/tether\"]", lockFile.ToToml());
    }

    /// <remarks>
    ///     Names and versions cannot contain a quote, but a checksum is whatever the package manager wrote, and a
    ///     lock file that does not parse back is worse than one that lost a character.
    /// </remarks>
    [Fact]
    public void ToToml_EscapesWhatAPackageManagerWrote()
    {
        var lockFile = new LockFile([new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3"), checksum: "sha256:\"a\\b\tc\"")]);

        var reread = ReadValid(lockFile.ToToml());

        Assert.Equal("sha256:\"a\\b\tc\"", reread.Find(PackageName.Parse("serio"))?.Checksum);
    }

    [Fact]
    public void WriteTo_WritesTheLockWhereTheReaderLooksForIt()
    {
        var directory = CreateTempDirectory();
        try
        {
            var written = new LockFile([new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3"))]).WriteTo(directory);

            Assert.Equal(Path.Combine(directory, LockFile.FileName), written);
            var lockFile = LockFileReader.LocateFromDirectory(directory, out var diagnostics);
            Assert.Empty(diagnostics);
            Assert.Equal("serio 1.2.3", Assert.Single(lockFile!.Packages).ToString());
        }
        finally
        {
            Directory.Delete(directory, true);
        }
    }

    [Fact]
    public void LocateFromDirectory_NullOrMissingDirectory_ReportsNothing()
    {
        Assert.Null(LockFileReader.LocateFromDirectory(null!));
        Assert.Null(LockFileReader.LocateFromDirectory(""));
        Assert.Null(LockFileReader.LocateFromDirectory(Path.Combine(Path.GetTempPath(), "loom-test-nonexistent-" + Guid.NewGuid())));
    }

    /// <remarks>A project that has never been resolved has no lock file, which is not a problem to report.</remarks>
    [Fact]
    public void LocateFromDirectory_DirectoryWithoutALockFile_ReportsNothing()
    {
        var directory = CreateTempDirectory();
        try
        {
            Assert.Null(LockFileReader.LocateFromDirectory(directory, out var diagnostics));
            Assert.Empty(diagnostics);
        }
        finally
        {
            Directory.Delete(directory, true);
        }
    }

    [Theory]
    [InlineData("[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\n", "must specify a 'version'")]
    [InlineData("version = 2\n", "lock file version 2 cannot be read")]
    [InlineData("version = 1\n[[package]]\nversion = \"1.2.3\"\n", "[[package]] must specify a 'name'")]
    [InlineData("version = 1\n[[package]]\nname = \"se rio\"\n", "invalid 'name' 'se rio'")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\n", "'serio' must specify a 'version'")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"^1.2\"\n", "invalid 'version' '^1.2'")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2\"\n", "exactly three components")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\nsource = \"   \"\n", "invalid 'source'")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\nchecksum = \"  \"\n", "empty 'checksum'")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\ndependencies = [\"te ther\"]\n", "which is not a package name")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\n[[package]]\nname = \"Serio\"\nversion = \"1.3.0\"\n", "is locked more than once")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\ndependencies = [\"runit\"]\n", "which the lock file does not lock")]
    [InlineData("version = 1\n[[package]]\nname = 3\nversion = \"1.2.3\"\n", "written as a string")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = 3\n", "written as a string")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\nchecksum = 3\n", "must have a 'checksum' written as a string")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\ndependencies = \"runit\"\n", "written as an array of package names")]
    [InlineData("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\ndependencies = [3]\n", "lists a dependency that is not a package name")]
    [InlineData("version = 1\n[[package\nname = \"serio\"\n", "Expected `]]`")]
    public void Read_MalformedLock_ReportsADiagnosticInsteadOfThrowing(string toml, string expectedMessage) => Assert.Contains(expectedMessage, ReadInvalid(toml).Message);

    /// <remarks>
    ///     A package manager writing a key this compiler has never heard of is what the format version is for, so
    ///     an unknown one is refused rather than skipped.
    /// </remarks>
    [Fact]
    public void Read_UnknownKey_IsRefused() =>
        Assert.Contains(
            "has an unknown key 'path'",
            ReadInvalid("version = 1\n[[package]]\nname = \"serio\"\nversion = \"1.2.3\"\npath = \"packages/serio\"\n").Message
        );

    [Fact]
    public void Constructor_LockingAPackageTwice_IsACallerBugRatherThanADiagnostic() =>
        Assert.Throws<ArgumentException>(
            () => new LockFile(
                [
                    new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3")),
                    new LockedPackage(PackageName.Parse("Serio"), Version.Parse("1.3.0"))
                ]
            )
        );

    [Fact]
    public void Satisfies_EveryRequirementMet_CoversTheProject()
    {
        var config = ReadManifest("[dependencies]\nserio = \"^1.2\"\nrunit = { version = \"^0.4\", dev = true }\n");
        var lockFile = new LockFile(
            [
                new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3")),
                new LockedPackage(PackageName.Parse("runit"), Version.Parse("0.4.7")),
                new LockedPackage(PackageName.Parse("alternativelua/tether"), Version.Parse("0.3.1"))
            ]
        );

        Assert.True(lockFile.Satisfies(config, out var unmet));
        Assert.Empty(unmet);
    }

    [Fact]
    public void Satisfies_UnlockedDependency_SaysWhichOne()
    {
        var config = ReadManifest("[dependencies]\nserio = \"^1.2\"\n");

        Assert.False(new LockFile([]).Satisfies(config, out var unmet));
        Assert.Contains("'serio' is not locked", Assert.Single(unmet).Message);
    }

    [Fact]
    public void Satisfies_LockedVersionTheRequirementRejects_SaysWhatDisagrees()
    {
        var config = ReadManifest("[dependencies]\nserio = \"^2\"\n");
        var lockFile = new LockFile([new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3"))]);

        Assert.False(lockFile.Satisfies(config, out var unmet));
        Assert.Contains("locked at 1.2.3, which '^2' does not accept", Assert.Single(unmet).Message);
    }

    /// <remarks>A dev dependency is part of the resolution, so a lock missing one is still out of date.</remarks>
    [Fact]
    public void Satisfies_CoversDevelopmentDependencies()
    {
        var config = ReadManifest("[dependencies]\nrunit = { version = \"^0.4\", dev = true }\n");

        Assert.False(new LockFile([]).Satisfies(config));
    }

    /// <remarks>
    ///     A package's development dependencies are no part of compiling it for someone else, so a lock that does not
    ///     pin them still covers it. The project being built is the exception, since it is the one being developed.
    /// </remarks>
    [Fact]
    public void Satisfies_CanIgnoreDevelopmentDependencies_AsAConsumerOfAPackageDoes()
    {
        var config = ReadManifest("[dependencies]\nserio = \"^1.2\"\nrunit = { version = \"^0.4\", dev = true }\n");
        var lockFile = new LockFile([new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3"))]);

        Assert.False(lockFile.Satisfies(config, includeDevelopmentOnly: true, out var unmet));
        Assert.Contains("'runit' is not locked", Assert.Single(unmet).Message);

        Assert.True(lockFile.Satisfies(config, includeDevelopmentOnly: false, out var ignored));
        Assert.Empty(ignored);
    }

    [Fact]
    public void ToString_DescribesWhatTheLockCovers()
    {
        Assert.Equal("loom-lock.toml (0 packages)", new LockFile([]).ToString());
        Assert.Equal("loom-lock.toml (1 package)", new LockFile([new LockedPackage(PackageName.Parse("serio"), Version.Parse("1.2.3"))]).ToString());
    }

    /// <remarks>
    ///     The layout is the other half of the contract the lock file is one half of: a package manager installs
    ///     into these directories and the compiler reads them, so neither has to ask the other where a package is.
    /// </remarks>
    [Fact]
    public void PackageLayout_PutsEveryLockedPackageUnderTheProjectsPackagesDirectory()
    {
        var config = ReadManifest("project_type = \"game\"\n");
        var lockFile = ReadValid(FullLock);

        var directories = PackageLayout.DirectoriesOf(config, lockFile);

        Assert.Equal(Path.Combine(config.ProjectDirectory, "packages", "serio"), directories[PackageName.Parse("serio")]);
        Assert.Equal(
            Path.Combine(config.ProjectDirectory, "packages", "alternativelua", "tether"),
            directories[PackageName.Parse("alternativelua/tether")]
        );
    }

    private static LockFile ReadValid(string toml)
    {
        var lockFile = LockFileReader.Read(toml, out var diagnostics);
        Assert.Empty(diagnostics);
        Assert.NotNull(lockFile);
        return lockFile;
    }

    private static ConfigDiagnostic ReadInvalid(string toml)
    {
        var lockFile = LockFileReader.Read(toml, out var diagnostics);
        Assert.Null(lockFile);
        return diagnostics[0];
    }

    /// <summary>Reads a manifest the way the compiler does, so its dependencies are the ones a lock is measured against.</summary>
    private static LoomConfig ReadManifest(string toml)
    {
        var directory = CreateTempDirectory();
        try
        {
            File.WriteAllText(Path.Combine(directory, ConfigReader.ConfigFileName), toml);
            var config = ConfigReader.LocateFromDirectory(directory, out var diagnostics);
            Assert.Empty(diagnostics);
            Assert.NotNull(config);
            return config;
        }
        finally
        {
            Directory.Delete(directory, true);
        }
    }

    private static string CreateTempDirectory()
    {
        var directory = Path.Combine(Path.GetTempPath(), "loom-test-" + Guid.NewGuid());
        Directory.CreateDirectory(directory);
        return directory;
    }
}
