using System.Text;

namespace Loom.Config;

/// <summary>
///     <c>loom-lock.toml</c>: the exact version every package in a build resolved to. Written by a package manager
///     and committed next to the manifest, so the manifest's requirements are re-resolved when they change rather
///     than on every machine that builds the project.
/// </summary>
/// <remarks>
///     This is the artifact that makes a package manager possible without putting one in the compiler: the manifest
///     says what is acceptable (see <see cref="Dependency.VersionRequirement" />), the lock says what was chosen,
///     and each is written by whoever can answer it. Entries are ordered by name and hold no machine-specific
///     paths, so a lock is a stable diff and the same file on every machine.
/// </remarks>
public sealed class LockFile
{
    public const string FileName = "loom-lock.toml";

    /// <summary>The format version this compiler writes, and the only one it reads.</summary>
    public const int CurrentFormatVersion = 1;

    private const string Header = "# Generated by a Loom package manager. Commit this file; do not edit it by hand.";

    private readonly Dictionary<PackageName, LockedPackage> _packages = [];

    /// <summary>
    ///     Builds a lock file over <paramref name="packages" />, one entry per package. Two entries for one package
    ///     is a caller bug rather than a manifest problem — nothing downstream supports a build resolving a package
    ///     twice — so it throws where <see cref="LockFileReader" /> reports a diagnostic.
    /// </summary>
    public LockFile(IEnumerable<LockedPackage> packages, int formatVersion = CurrentFormatVersion)
    {
        foreach (var package in packages)
        {
            if (!_packages.TryAdd(package.Name, package))
                throw new ArgumentException($"'{package.Name}' is locked more than once.", nameof(packages));
        }

        FormatVersion = formatVersion;
        Packages = _packages.Values.OrderBy(package => package.Name).ToArray();
    }

    /// <summary>The <c>version</c> the lock file declares; <see cref="CurrentFormatVersion" /> for one written here.</summary>
    public int FormatVersion { get; }

    /// <summary>Every locked package, ordered by name so the file a package manager writes does not churn.</summary>
    public IReadOnlyList<LockedPackage> Packages { get; }

    /// <summary>The version <paramref name="name" /> is locked at, or <see langword="null" /> when it is not locked.</summary>
    public LockedPackage? Find(PackageName name) => _packages.GetValueOrDefault(name);

    /// <summary>
    ///     Whether every dependency <paramref name="config" /> declares — development ones included, since a project
    ///     develops itself with them — is locked at a version its requirement accepts.
    /// </summary>
    /// <remarks>
    ///     A package locked that nothing depends on any more is not a disagreement, only something for a package
    ///     manager to prune, so it is not reported here.
    /// </remarks>
    public bool Satisfies(LoomConfig config) => Satisfies(config, true, out _);

    /// <inheritdoc cref="Satisfies(LoomConfig)" />
    public bool Satisfies(LoomConfig config, out IReadOnlyList<ConfigDiagnostic> unmet) => Satisfies(config, true, out unmet);

    /// <inheritdoc cref="Satisfies(LoomConfig)" />
    /// <param name="config">The project whose requirements the lock is measured against.</param>
    /// <param name="includeDevelopmentOnly">
    ///     Whether <c>dev = true</c> dependencies count. They do for the project being built, which is being
    ///     developed; they do not for a package it depends on, whose test framework is no part of compiling it.
    /// </param>
    /// <param name="unmet">Why the lock does not cover the project, one entry per requirement it fails.</param>
    public bool Satisfies(LoomConfig config, bool includeDevelopmentOnly, out IReadOnlyList<ConfigDiagnostic> unmet)
    {
        var reported = new List<ConfigDiagnostic>();
        unmet = reported;
        foreach (var (name, dependency) in config.Dependencies)
        {
            if (dependency.IsDevelopmentOnly && !includeDevelopmentOnly)
                continue;

            var locked = Find(name);
            if (locked == null)
                reported.Add(new ConfigDiagnostic($"'{name}' is not locked."));
            else if (!dependency.VersionRequirement.Satisfies(locked.Version))
                reported.Add(new ConfigDiagnostic($"'{name}' is locked at {locked.Version}, which '{dependency.VersionRequirement}' does not accept."));
        }

        return reported.Count == 0;
    }

    /// <summary>
    ///     The lock file as TOML. Deterministic down to the byte — ordered entries, a fixed key order and
    ///     line feeds whatever the platform — because it is a committed file two machines must agree on.
    /// </summary>
    public string ToToml()
    {
        var builder = new StringBuilder().Append(Header).Append('\n').Append("version = ").Append(FormatVersion).Append('\n');
        foreach (var package in Packages)
        {
            builder.Append("\n[[package]]\n");
            builder.Append("name = ").Append(Quote(package.Name.ToString())).Append('\n');
            builder.Append("version = ").Append(Quote(package.Version.ToString())).Append('\n');
            if (package.Source != null)
                builder.Append("source = ").Append(Quote(package.Source)).Append('\n');

            if (package.Checksum != null)
                builder.Append("checksum = ").Append(Quote(package.Checksum)).Append('\n');

            if (package.Dependencies.Count > 0)
            {
                builder.Append("dependencies = [")
                    .AppendJoin(", ", package.Dependencies.Select(name => Quote(name.ToString())))
                    .Append("]\n");
            }
        }

        return builder.ToString();
    }

    /// <summary>
    ///     Writes the lock file into <paramref name="directoryPath" /> and returns the path written. An I/O failure
    ///     is the caller's to handle: unlike reading a manifest, writing is something a tool chose to do, and it is
    ///     the one holding the context to say what could not be written where.
    /// </summary>
    public string WriteTo(string directoryPath)
    {
        var path = Path.Combine(directoryPath, FileName);
        File.WriteAllText(path, ToToml());
        return path;
    }

    public override string ToString() => $"{FileName} ({Packages.Count} package{(Packages.Count == 1 ? "" : "s")})";

    /// <summary>
    ///     A TOML basic string. Names and versions cannot contain anything needing an escape, but a checksum and a
    ///     source are whatever the package manager wrote, and a lock file that does not parse back is worse than
    ///     one that lost a character.
    /// </summary>
    private static string Quote(string value)
    {
        var builder = new StringBuilder(value.Length + 2).Append('"');
        foreach (var character in value)
        {
            builder.Append(
                character switch
                {
                    '"' => "\\\"",
                    '\\' => "\\\\",
                    '\n' => "\\n",
                    '\r' => "\\r",
                    '\t' => "\\t",
                    _ => char.IsControl(character) ? $"\\u{(int)character:x4}" : character.ToString()
                }
            );
        }

        return builder.Append('"').ToString();
    }
}
